# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[zh-Hant]
  languageCode = "zh-Tw"
  contentDir = "content/zh-Hant"
  title = "Sunny Fu"
  [zh-Hant.params]
    description = "Site description in Chinese..."
  [[zh-Hant.menu.main]]
    name = "關於我"
    url = "#about"
    weight = 10
  [[zh-Hant.menu.main]]
    name = "文章"
    url = "#posts"
    weight = 20